---

name: Deploy Vkit

on: 
  push: 
    branches: 
      - main

jobs:
  deploy-vkit: 
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@main

      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: create allCards.json
        run: |
          npm install aws-sdk
          node create_json.js
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: sync to s3
        run: |+
          aws s3 sync . s3://vkit.starwarsccg.org/ --exclude '.git/*' --exclude '.github/*' --exclude 'node_modules/*' --exclude README.md --exclude package.json --exclude package-lock.json --exclude create_json.js --exclude s3_website.yml
          aws cloudfront create-invalidation --distribution-id E28JJ75W3J9G61 --paths "/" "/allCards.json"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}



